version: 0.2

phases:
  install:
    commands:
      # Install dependencies needed for running test
      - pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      # Discover and run unit tests. For more information, see <https://docs.djangoproject.com/en/2.0/topics/testing/overview/>
      - python manage.py test

artifacts:
  type: zip
  files:
    - '.ebextensions/**/*'
    - 'ebdjango/**/*'
    - 'helloworld/**/*'
    - 'community/**/*'
    - 'manage.py'
    - 'requirements.txt'
